### ISSUE TITLE
好棒

### ISSUE THREAD

**Issue by ufiredong** [Lonor/websocket-cluster#1]
学习了，代码比我规范多了。

**Comment by Lonor** [comment]
> 学习了，代码比我规范多了。

也是学习您的项目轮廓，参考大家的文章实践的。Hash 环那边换了一个实现方式。

原本用广播队列作全局 WebSocket 通知实现起来比较简单，就没想再尝试此方案。但是在实现节点上线，更新 Hash 环通知客户端移动到新的节点的时候，发现还是得用到集群内广播……

整个项目写了五天，还是比较有收获的。

**Comment by Lonor** [comment]
之前有人提出把哈希环维护在 Nacos 上，但 Nacos 维护者似乎没能明白这个需求：
https://github.com/alibaba/nacos/issues/2114

**Comment by ufiredong** [comment]
嗯嗯，我正在研究你的实现，  Nacos 集群里用到 一致性了， 我倒是觉得维护一个hash环可以通过插件去完成，毕竟naocs的主要是用来做服务注册与发现的。
