### ISSUE TITLE
方案中关于websocket服务的上下线通知

### ISSUE THREAD

**Issue by fuyuanwu** [Lonor/websocket-cluster#12]
方案中关于websocket服务的上下线通知，可否考虑直接通过nacos来做，nacos也是支持监听服务下的实例列表变化的，这样可以：

1. 规避了增加websocket服务实例到websocket服务可用的时差问题 [https://nacos.io/zh-cn/docs/sdk.html](url)
2. 方案可解除对redis的依赖，

**Comment by fuyuanwu** [comment]
这个理解了。
> Redis 内还有存放了一些哈希环数据， 哈希环是全局的

注意到之前你们给nacos提了一个维护哈希环的需求，他们出于核心业务考虑，没决定实现；那么咱们对于”哈希环是全局存储“，是否可以考虑将他以配置的方式存储到配置中心。这样可以借助其分发和持久化能力，且咱们这个环数据应该也不大。
不知这是否有可行性~

**Comment by fuyuanwu** [comment]
![序列图](https://user-images.githubusercontent.com/7333474/135245781-9e51daa5-423e-4870-a21b-0d81efd2f8fe.jpg)

**Comment by fuyuanwu** [comment]
可以考虑把client的信息从环上面拿下来，这样环就更轻量级了；如果需要client的汇总信息，则实时的从各wsServer实例去查询，或者让各wsServer实例心跳的汇报给gateway。
明天再调整一下~

**Comment by fuyuanwu** [comment]
![image](https://user-images.githubusercontent.com/7333474/135387861-300f019d-9412-4961-94ed-ff3bcf5bbbf5.png)

**Comment by Lonor** [comment]
/close this due to inactive status.

<details><summary>More</summary><p>Feel free to re-open this issue by comment with &#47;re-open </p></details>
