### ISSUE TITLE
服务端主动推送消息，请问是如何确定用户的长连接在那台服务器的？

### ISSUE THREAD

**Issue by LuGengYuan** [Lonor/websocket-cluster#24]
您好，我看了下代码，里面是通过重写负载均衡器来实现请求定位到某台服务器（不对的话请指教），但是因为我们涉及到某个操作触发服务端主动像客户端推送消息，这时候后端通过feign去调用的发送信息接口，不通过网关，怎么定位该用户长连接存在的服务器，从而成功给用户推送消息？

**Comment by Lonor** [comment]
/label question
哈希环维护在 Redis 中，网关这边的作用首先是根据注册中心的 WebScoket 服务实例状态来更新哈希环，第二就是你说的负载均衡也在网关实现了 - 就是基于哈希环。

不通过网关，服务服务之间直接  RPC 的话也一样：只要能够将实时的 WebSocket 服务实例 和 客户端连接信息 的 映射关系想办法维护起来并获取到就行。

**Comment by Lonor** [comment]
举个例子：

2 个 WebSocket 做负载均衡，3 个客户端用户连接
WebSocketServer 1 (192.168.0.1) - [ User A ]
WebSocketServer 2 (192.168.0.2) - [ User B, User C]

往用户 C 推消息就是直接针对 IP 为 192.168.0.2 的 WebSocket 服务实例发起 Feign 请求。

**Comment by LuGengYuan** [comment]
但是，服务服务之间的话，我的请求路由到的服务不一定是该用户长连接建立的服务器，就没有该用户的session ，这里是怎么处理的？

**Comment by Lonor** [comment]
你总得有一个地方去知道那个客户端的连接（WebSocket Session）存储在哪个服务实例的内存中。并且任何 WebSocket 实例有变动（宕机/扩缩容/副本数量变化），都要及时更新这个映射（Mapping，这里就是哈希环）。

**Comment by Lonor** [comment]
哈希环的路由：根据客户端的 ID（BusinessKey/UserId...）来映射到存在此 session 的 WebScoket 实例节点：

https://github.com/Lonor/websocket-cluster/blob/7a8d44677a719c0d72d8133b43da240b6f6b7fdf/common/src/main/java/me/lawrenceli/hashring/ConsistentHashRouter.java#L48-L54

**Comment by LuGengYuan** [comment]
> 哈希环的路由：根据客户端的 ID（BusinessKey/UserId...）来映射到存在此 session 的 WebScoket 实例节点：
> 
> https://github.com/Lonor/websocket-cluster/blob/7a8d44677a719c0d72d8133b43da240b6f6b7fdf/common/src/main/java/me/lawrenceli/hashring/ConsistentHashRouter.java#L48-L54

那我可以这样理解吗，我如果服务服务之间调用的话，也需要通过该方法拿到对应ip后，在通过feign发起指定ip的请求

**Comment by Lonor** [comment]
> > 哈希环的路由：根据客户端的 ID（BusinessKey/UserId...）来映射到存在此 session 的 WebScoket 实例节点：
> > https://github.com/Lonor/websocket-cluster/blob/7a8d44677a719c0d72d8133b43da240b6f6b7fdf/common/src/main/java/me/lawrenceli/hashring/ConsistentHashRouter.java#L48-L54
> 
> 那我可以这样理解吗，我如果服务服务之间调用的话，也需要通过该方法拿到对应ip后，在通过feign发起指定ip的请求

对。你把网关里的负载均衡移植到 Feign 的负载均衡实现中去，结合 Ribbon 实现一个自己的 NFLoadBalancerRuleClass。Google 搜搜看看。

**Comment by LuGengYuan** [comment]
好的，那我就明白了，感谢感谢，之前我以为你已经在代码中处理过，是我没看到

**Comment by Lonor** [comment]
Resolved.
/close
